name: Continuous Integration (CI)

on: pull_request

permissions:
  contents: read

jobs:
  formatting:
    name: Formatting
    runs-on: ${{ matrix.architecture }}
    strategy:
      matrix:
        architecture: [ubuntu-24.04, ubuntu-24.04-arm]
        language: [shell]
    steps:
      - name: Checkout code.
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install shfmt.
        run: sudo apt-get update && sudo apt-get install -y shfmt
      - name: Check formatting.
        run: make check-${{ matrix.language }}-formatting

  linting:
    name: Linting
    runs-on: ${{ matrix.architecture }}
    strategy:
      matrix:
        architecture: [ubuntu-24.04, ubuntu-24.04-arm]
        language: [shell]
    steps:
      - name: Checkout code.
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install shellcheck.
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Check linting.
        run: make check-${{ matrix.language }}-linting

  scripts-permissions:
    name: Scripts Permissions
    runs-on: ${{ matrix.architecture }}
    strategy:
      matrix:
        architecture: [ubuntu-24.04, ubuntu-24.04-arm]
    steps:
      - name: Checkout code.
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Check scripts permissions.
        run: make check-scripts-permissions
